baseURL = "http://example.org/"
languageCode = "ru"
title = "Help OVZ"
theme = "ananke"
[menu]

  [[menu.main]]
    identifier = "home"
    name       = "Главная"
    url        = "/"
    weight     = 1

  [[menu.main]]
    identifier = "about"
    name       = "О проекте"
    url        = "/about/"
    weight     = 2

  [[menu.main]]
    identifier = "participants"
    name       = "Участники"
    url        = "/participants/"
    weight     = 3

  [[menu.main]]
    identifier = "journal"
    name       = "Журнал"
    url        = "/journal/"
    weight     = 4

  [[menu.main]]
    identifier = "resources"
    name       = "Ресурсы"
    url        = "/resources/"
    weight     = 5
  [[menu.main]]
    identifier = "optional"
    name       = "Вариативная часть"
    url        = "/optional/"
    weight     = 6
